target-version = "py311"

[lint]
ignore = ["E501"]
select = ["ALL"]

# Allow fix for all enabled rules (when `--fix`) is provided.
unfixable = ["F401", "W391", "F841"]
fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
